spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commentDb
    username: root
    password: test
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create-drop, validate, none
    database-platform: org.hibernate.dialect.MySQL8Dialect # or appropriate MySQL dialect
    show-sql: true # to show SQL queries in console
   # properties:
     # hibernate:
     #   dialect: org.hibernate.dialect.MySQL8Dialect # or appropriate MySQL dialect
      #  format_sql: true # to format SQL queries
server:
  port: 8082
